# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-10-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def add_region_and_root_id_value(apps, schema_editor):
    S3NodeSettings = apps.get_model('addons_s3compatinstitutions', 'nodesettings')
    OsfNodeSettings = apps.get_model('addons_osfstorage', 'nodesettings')
    for osfnodesettings in OsfNodeSettings.objects.all():
        s3nodesettings = S3NodeSettings.objects.filter(owner_id=osfnodesettings.owner_id)
        if s3nodesettings.exists():
            for s3 in s3nodesettings:
                s3.region_id = osfnodesettings.region_id
                s3.root_node_id = osfnodesettings.root_node_id
                s3.save()

def noop(*args):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0008_auto_20230323_0918'),
        ('addons_s3compatinstitutions', '0002_auto_20210312_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_institutions_region_id', to='addons_osfstorage.Region'),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='root_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_institutions_root_node_id', to='osf.BaseFileNode'),
        ),
        migrations.AlterField(
            model_name='nodesettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_institutions_addon_node_settings', to='osf.AbstractNode'),
        ),
        migrations.RunPython(add_region_and_root_id_value, noop)
    ]
