# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-10-06 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_region_and_root_id_value(apps, schema_editor):
    DropboxBusinessNodeSettings = apps.get_model('addons_dropboxbusiness', 'nodesettings')
    OsfNodeSettings = apps.get_model('addons_osfstorage', 'nodesettings')
    for osfnodesettings in OsfNodeSettings.objects.all():
        dropboxbusinessnodesettings = DropboxBusinessNodeSettings.objects.filter(owner_id=osfnodesettings.owner_id)
        if dropboxbusinessnodesettings.exists():
            for dropbox in dropboxbusinessnodesettings:
                dropbox.region_id = osfnodesettings.region_id
                dropbox.root_node_id = osfnodesettings.root_node_id
                dropbox.save()


def noop(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0008_auto_20230323_0918'),
        ('addons_dropboxbusiness', '0002_rename_deleted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesettings',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_business_region_id', to='addons_osfstorage.Region'),
        ),
        migrations.AddField(
            model_name='nodesettings',
            name='root_node',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_business_root_node_id', to='osf.BaseFileNode'),
        ),
        migrations.AlterField(
            model_name='nodesettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropbox_business_addon_node_settings', to='osf.AbstractNode'),
        ),
        migrations.RunPython(add_region_and_root_id_value, noop)
    ]
