# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-02-24 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base
from osf.models.storage import StorageType
from api.base import settings as api_settings


def move_quota_from_user_quota_table(apps, schema_editor):
    UserQuota = apps.get_model('osf', 'UserQuota')
    UserStorageQuota = apps.get_model('osf', 'UserStorageQuota')
    Region = apps.get_model('addons_osfstorage.region')
    OSFUser = apps.get_model('osf.OSFUser')
    region_id = None
    for user_quota in UserQuota.objects.all():
        user = OSFUser.objects.get(id=user_quota.user_id)
        if user_quota.storage_type == StorageType.NII_STORAGE:
            region_id = api_settings.NII_STORAGE_REGION_ID
        else:
            institution = user.affiliated_institutions.first()
            if institution:
                region = Region.objects.get(_id=institution._id)
                region_id = region.id
        UserStorageQuota.objects.create(
            user=user,
            region_id=region_id,
            max_quota=user_quota.max_quota,
            used=user_quota.used
        )
        user_quota.save()


def noop(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0006_rename_deleted_field'),
        ('osf', '0224_ensure_schema_and_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('max_quota', models.IntegerField(default=0)),
                ('used', models.BigIntegerField(default=0)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AlterUniqueTogether(
            name='userstoragequota',
            unique_together=set([('user', 'region')]),
        ),
        migrations.RunPython(move_quota_from_user_quota_table, noop)
    ]
