# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations


def add_parent_id_value(apps, schema_editor):
    BaseFileNode = apps.get_model('osf', 'basefilenode')
    rootbasefilenodes = BaseFileNode.objects.filter(is_root=True)
    if rootbasefilenodes.exists():
        for rootbasefilenode in rootbasefilenodes:
            basefilenodes = BaseFileNode.objects.filter(is_root=None, target_object_id=rootbasefilenode.target_object_id)
            if basefilenodes.exists():
                for basefilenode in basefilenodes:
                    basefilenode.parent_id = rootbasefilenode.id
                    basefilenode.save()


def noop(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0226_auto_20230323_0918'),
    ]

    operations = [
        migrations.RunPython(add_parent_id_value, noop)
    ]
