# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-06-29 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from osf.models.storage import StorageType
from api.base import settings as api_settings


def add_region_id_value(apps, schema_editor):
    Userquota = apps.get_model('osf', 'UserQuota')
    Region = apps.get_model('addons_osfstorage.region')
    OSFUser = apps.get_model('osf.OSFUser')
    for user_quota in Userquota.objects.all():
        if user_quota.storage_type == StorageType.NII_STORAGE:
            user_quota.region_id = api_settings.NII_STORAGE_REGION_ID
        else:
            user = OSFUser.objects.get(id=user_quota.user_id)
            institution = user.affiliated_institutions.first()
            if institution:
                region = Region.objects.get(_id=institution._id)
                user_quota.region_id = region.id
        user_quota.save()

def noop(*args):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('addons_osfstorage', '0008_auto_20230323_0918'),
        ('osf', '0226_auto_20230323_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquota',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addons_osfstorage.Region'),
        ),

        migrations.RunPython(add_region_id_value, noop)
    ]
