# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-03-23 09:18
from __future__ import unicode_literals

from django.db import migrations


def add_parent_id_value(apps, schema_editor):
    BaseFileNode = apps.get_model('osf', 'BaseFileNode')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    content_type = ContentType.objects.get(app_label='osf', model='abstractnode')
    root_base_file_nodes = BaseFileNode.objects.filter(is_root=True)
    for root_base_file_node in root_base_file_nodes:
        BaseFileNode.objects.filter(
            is_root=None,
            target_object_id=root_base_file_node.target_object_id,
            target_content_type=content_type,
        ).update(
            parent_id=root_base_file_node.id
        )


def noop(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0226_auto_20230323_0918'),
    ]

    operations = [
        migrations.RunPython(add_parent_id_value, noop)
    ]
