# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-10-06 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0227_auto_20230724_0930'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rdmaddonoption',
            unique_together=set([]),
        ),
    ]
