# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2024-02-27 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0232_auto_20230830_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('function_code', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['pk'],
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.CreateModel(
            name='ServiceAccessControlSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('institution_id', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('is_ial2_or_aal2', models.BooleanField()),
                ('user_domain', models.CharField(max_length=255)),
                ('project_limit_number', models.IntegerField(null=True)),
                ('is_whitelist', models.BooleanField()),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'osf_service_access_control_setting',
                'ordering': ['pk'],
            },
            bases=(models.Model, osf.models.base.QuerySetExplainMixin),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='aal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='osfuser',
            name='ial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceaccesscontrolsetting',
            index=models.Index(fields=['institution_id', 'domain', 'is_ial2_or_aal2', 'user_domain'], name='osf_service_institu_0bf9fc_idx'),
        ),
        migrations.AddField(
            model_name='function',
            name='service_access_control_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='osf.ServiceAccessControlSetting'),
        ),
    ]
