# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2023-10-06 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addons_onedrivebusiness', '0003_auto_20230724_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodesettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_drive_business_node_settings', to='osf.AbstractNode'),
        ),
    ]
